# Site settings
title: EMILY M.
email: msemilymartinez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site was built with Jekyll. 
baseurl: "/portfolio" # the subpath of your site, e.g. /blog/
url: "http://em3021.github.io" # the base hostname & protocol for your site
twitter_username: martinez_emily
github_username:  em3021
collections:
  - writing
collections: 
writing:
output: true
permalink: /writing/:path/

# Build settings
markdown: kramdown
