# Site settings
title: EMILY M.
email: msemilymartinez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site was built with Jekyll. 
baseurl: "/portfolio" # the subpath of your site, e.g. /blog/
url: "http://em3021.github.io" # the base hostname & protocol for your site
twitter_username: martinez_emily
github_username:  em3021
collections:
  - writing
collections: 
writing:
output: true
permalink: /writing/:path/

# Build settings
markdown: kramdown
picture:
  source: assets/img/_originals
  output: assets/img/generated
  markup: picturefill
  presets:
    default:
      source_large_2x: 
        media: "(min-width: 37.5em) and (-webkit-min-device-pixel-ratio: 1.3), (min-width: 37.5em) and (min-resolution: 124.8dpi)" # 600px@2x
        width: 1800
      source_large:
        media: "(min-width: 37.5em)" # 600px
        width: 900
      source_default_2x:
        media: "(-webkit-min-device-pixel-ratio: 1.3), (min-resolution: 124.8dpi)"
        width: 960
      source_default: 
        width: 480
    hero:
      source_large_2x: 
        media: "(min-width: 37.5em) and (-webkit-min-device-pixel-ratio: 1.3), (min-width: 37.5em) and (min-resolution: 124.8dpi)" # 600px@2x
        width: 2400
      source_large:
        media: "(min-width: 37.5em)" # 600px
        width: 1200
      source_medium_2x:
        media: "(min-width: 30em) and (-webkit-min-device-pixel-ratio: 1.3), (min-width: 30em) and (min-resolution: 124.8dpi)" # 480px@2x
        width: 1600
      source_medium:
        media: "(min-width: 30em)" # 480px
        width: 800
      source_default_2x:
        media: "(-webkit-min-device-pixel-ratio: 1.3), (min-resolution: 124.8dpi)"
        width: 960
      source_default: 
        width: 480
    inset:
      source_default_2x:
        media: "(-webkit-min-device-pixel-ratio: 1.3), (min-resolution: 124.8dpi)"
        width: 720
      source_default: 
        width: 360